"""Auto migration

Revision ID: 0341a3ac3db4
Revises: 63a3184efbc7
Create Date: 2025-09-04 17:03:33.977063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0341a3ac3db4'
down_revision: Union[str, Sequence[str], None] = '63a3184efbc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
