"""add_ean_column_nullable

Revision ID: 07a9aef9ee3b
Revises: d124ceaed7ed
Create Date: 2025-07-11 13:29:46.333463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07a9aef9ee3b'
down_revision: Union[str, Sequence[str], None] = 'd124ceaed7ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_references')
    op.add_column('product_calculations', sa.Column('supplier_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product_calculations', 'suppliers', ['supplier_id'], ['id'])
    op.add_column('products', sa.Column('ean', sa.String(length=20), nullable=True))
    op.drop_constraint(op.f('uix_product_reference_supplier'), 'products', type_='unique')
    op.drop_constraint(op.f('products_supplier_id_fkey'), 'products', type_='foreignkey')
    op.drop_column('products', 'reference_id')
    op.drop_column('products', 'supplier_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('reference_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('products_supplier_id_fkey'), 'products', 'suppliers', ['supplier_id'], ['id'])
    op.create_unique_constraint(op.f('uix_product_reference_supplier'), 'products', ['reference_id', 'supplier_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('products', 'ean')
    op.drop_constraint(None, 'product_calculations', type_='foreignkey')
    op.drop_column('product_calculations', 'supplier_id')
    op.create_table('product_references',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('selling_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ean', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('product_references_supplier_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('product_references_pkey')),
    sa.UniqueConstraint('ean', 'supplier_id', name=op.f('uix_reference_ean_supplier'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
