"""Auto migration

Revision ID: 18335cf2e60f
Revises: 6d10bd16822b
Create Date: 2025-09-04 17:30:36.601119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18335cf2e60f'
down_revision: Union[str, Sequence[str], None] = '6d10bd16822b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.String(length=120), nullable=True))
    op.drop_column('products', 'designation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('designation', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('products', 'description')
    # ### end Alembic commands ###
