"""Auto migration

Revision ID: 1cd1bccfa105
Revises: a2dd35913739
Create Date: 2025-07-16 18:06:12.335973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cd1bccfa105'
down_revision: Union[str, Sequence[str], None] = 'a2dd35913739'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('recommended_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'recommended_price')
    # ### end Alembic commands ###
