"""Auto migration

Revision ID: 68a0bb6b533c
Revises: cd9ecb9721d0
Create Date: 2025-09-22 15:46:08.460170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68a0bb6b533c'
down_revision: Union[str, Sequence[str], None] = 'cd9ecb9721d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('part_number', sa.String(length=120), nullable=True))
    op.add_column('temporary_imports', sa.Column('part_number', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temporary_imports', 'part_number')
    op.drop_column('products', 'part_number')
    # ### end Alembic commands ###
