"""add_model

Revision ID: 6c3deea15a64
Revises: 07a9aef9ee3b
Create Date: 2025-07-11 14:58:05.438369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c3deea15a64'
down_revision: Union[str, Sequence[str], None] = '07a9aef9ee3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('model', sa.String(length=120), nullable=True))
    op.drop_column('products', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_column('products', 'model')
    # ### end Alembic commands ###
