"""Auto migration

Revision ID: 6d10bd16822b
Revises: 0341a3ac3db4
Create Date: 2025-09-04 17:21:40.180657

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6d10bd16822b'
down_revision: Union[str, Sequence[str], None] = '0341a3ac3db4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_calculations', sa.Column('marge', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_calculations', 'marge')
    # ### end Alembic commands ###
