"""tcp integer

Revision ID: 820d21458e94
Revises: b763d9ca61cc
Create Date: 2025-07-13 07:28:25.608372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '820d21458e94'
down_revision: Union[str, Sequence[str], None] = 'b763d9ca61cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('memory_options', 'tcp_value',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('memory_options', 'tcp_value',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
