"""table format_imports

Revision ID: 8496c69e3c5b
Revises: dc15f45b1a72
Create Date: 2025-07-14 19:50:08.822048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8496c69e3c5b'
down_revision: Union[str, Sequence[str], None] = 'dc15f45b1a72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('format_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('column_name', sa.String(length=50), nullable=True),
    sa.Column('column_type', sa.String(length=50), nullable=True),
    sa.Column('column_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('format_imports')
    # ### end Alembic commands ###
