"""Auto migration

Revision ID: 9bc8af58f6e0
Revises: d9164147286f
Create Date: 2025-09-03 17:40:26.753917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bc8af58f6e0'
down_revision: Union[str, Sequence[str], None] = 'd9164147286f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temporary_imports', sa.Column('ram_id', sa.Integer(), nullable=True))
    op.add_column('temporary_imports', sa.Column('norme_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'temporary_imports', 'ram_options', ['ram_id'], ['id'])
    op.create_foreign_key(None, 'temporary_imports', 'norme_options', ['norme_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'temporary_imports', type_='foreignkey')
    op.drop_constraint(None, 'temporary_imports', type_='foreignkey')
    op.drop_column('temporary_imports', 'norme_id')
    op.drop_column('temporary_imports', 'ram_id')
    # ### end Alembic commands ###
