"""Auto migration

Revision ID: aae76926f8c0
Revises: b10b2b96dec6
Create Date: 2025-09-02 16:25:05.922605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aae76926f8c0'
down_revision: Union[str, Sequence[str], None] = 'b10b2b96dec6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('designation', sa.String(length=120), nullable=True))
    op.add_column('products', sa.Column('RAM_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('norme_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'ram_options', ['RAM_id'], ['id'])
    op.create_foreign_key(None, 'products', 'norme_options', ['norme_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'norme_id')
    op.drop_column('products', 'RAM_id')
    op.drop_column('products', 'designation')
    # ### end Alembic commands ###
