"""add tcp in memory table

Revision ID: b763d9ca61cc
Revises: 728184c1b820
Create Date: 2025-07-13 07:22:03.627096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b763d9ca61cc'
down_revision: Union[str, Sequence[str], None] = '728184c1b820'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memory_options', sa.Column('tcp_value', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memory_options', 'tcp_value')
    # ### end Alembic commands ###
