"""Rename temporary_imports to supplier_catalog

Revision ID: i1_rename_temp
Revises: h1a2b3c4d5f0
Create Date: 2026-02-14
"""

from alembic import op
from sqlalchemy import inspect

revision = "i1_rename_temp"
down_revision = "h1a2b3c4d5f0"
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    inspector = inspect(conn)
    existing_tables = inspector.get_table_names()

    # If db.create_all() already created an empty supplier_catalog, drop it first
    if "supplier_catalog" in existing_tables and "temporary_imports" in existing_tables:
        op.drop_table("supplier_catalog")

    # If temporary_imports doesn't exist (already renamed), skip rename
    if "temporary_imports" not in existing_tables:
        return

    # 1. Rename the table
    op.rename_table("temporary_imports", "supplier_catalog")

    # 2. Rename the sequence (auto-generated by PostgreSQL for SERIAL/IDENTITY)
    op.execute(
        "ALTER SEQUENCE temporary_imports_id_seq RENAME TO supplier_catalog_id_seq"
    )

    # 3. Rename the primary key index
    op.execute(
        "ALTER INDEX temporary_imports_pkey RENAME TO supplier_catalog_pkey"
    )

    # 4. Rename the unique constraint index
    op.execute(
        "ALTER INDEX uix_temp_ean_supplier RENAME TO uix_supplier_catalog_ean_supplier"
    )

    # 5. Rename foreign key constraints on supplier_catalog
    op.execute(
        "ALTER TABLE supplier_catalog RENAME CONSTRAINT "
        "temporary_imports_brand_id_fkey TO supplier_catalog_brand_id_fkey"
    )
    op.execute(
        "ALTER TABLE supplier_catalog RENAME CONSTRAINT "
        "temporary_imports_color_id_fkey TO supplier_catalog_color_id_fkey"
    )
    op.execute(
        "ALTER TABLE supplier_catalog RENAME CONSTRAINT "
        "temporary_imports_memory_id_fkey TO supplier_catalog_memory_id_fkey"
    )
    op.execute(
        "ALTER TABLE supplier_catalog RENAME CONSTRAINT "
        "temporary_imports_norme_id_fkey TO supplier_catalog_norme_id_fkey"
    )
    op.execute(
        "ALTER TABLE supplier_catalog RENAME CONSTRAINT "
        "temporary_imports_ram_id_fkey TO supplier_catalog_ram_id_fkey"
    )
    op.execute(
        "ALTER TABLE supplier_catalog RENAME CONSTRAINT "
        "temporary_imports_supplier_id_fkey TO supplier_catalog_supplier_id_fkey"
    )
    op.execute(
        "ALTER TABLE supplier_catalog RENAME CONSTRAINT "
        "temporary_imports_type_id_fkey TO supplier_catalog_type_id_fkey"
    )

    # 6. Rename the FK constraint on pending_matches that references this table
    op.execute(
        "ALTER TABLE pending_matches RENAME CONSTRAINT "
        "pending_matches_temporary_import_id_fkey "
        "TO pending_matches_temporary_import_id_fkey_sc"
    )


def downgrade():
    # Reverse: rename FK on pending_matches
    op.execute(
        "ALTER TABLE pending_matches RENAME CONSTRAINT "
        "pending_matches_temporary_import_id_fkey_sc "
        "TO pending_matches_temporary_import_id_fkey"
    )

    # Reverse: rename FKs on supplier_catalog
    op.execute(
        "ALTER TABLE supplier_catalog RENAME CONSTRAINT "
        "supplier_catalog_type_id_fkey TO temporary_imports_type_id_fkey"
    )
    op.execute(
        "ALTER TABLE supplier_catalog RENAME CONSTRAINT "
        "supplier_catalog_supplier_id_fkey TO temporary_imports_supplier_id_fkey"
    )
    op.execute(
        "ALTER TABLE supplier_catalog RENAME CONSTRAINT "
        "supplier_catalog_ram_id_fkey TO temporary_imports_ram_id_fkey"
    )
    op.execute(
        "ALTER TABLE supplier_catalog RENAME CONSTRAINT "
        "supplier_catalog_norme_id_fkey TO temporary_imports_norme_id_fkey"
    )
    op.execute(
        "ALTER TABLE supplier_catalog RENAME CONSTRAINT "
        "supplier_catalog_memory_id_fkey TO temporary_imports_memory_id_fkey"
    )
    op.execute(
        "ALTER TABLE supplier_catalog RENAME CONSTRAINT "
        "supplier_catalog_color_id_fkey TO temporary_imports_color_id_fkey"
    )
    op.execute(
        "ALTER TABLE supplier_catalog RENAME CONSTRAINT "
        "supplier_catalog_brand_id_fkey TO temporary_imports_brand_id_fkey"
    )

    # Reverse: rename unique constraint
    op.execute(
        "ALTER INDEX uix_supplier_catalog_ean_supplier RENAME TO uix_temp_ean_supplier"
    )

    # Reverse: rename primary key
    op.execute(
        "ALTER INDEX supplier_catalog_pkey RENAME TO temporary_imports_pkey"
    )

    # Reverse: rename sequence
    op.execute(
        "ALTER SEQUENCE supplier_catalog_id_seq RENAME TO temporary_imports_id_seq"
    )

    # Reverse: rename table
    op.rename_table("supplier_catalog", "temporary_imports")
